import { Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";

const robotoCondensed = Roboto_Condensed({
	variable: "--font-roboto-condensed",
	subsets: ["latin"],
	weight: ["300", "400", "700"],
});

export const metadata = {
	title: "Shrunk ur URL",
	description: "Generated by tinyknot to get ur URL short",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={`${robotoCondensed.variable}  antialiased`}>
				<Nav />
				{children}
			</body>
		</html>
	);
}
